language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Example.xcodeproj
  - IOS_FRAMEWORK_SCHEME="Argonaut-iOS"
  - TVOS_FRAMEWORK_SCHEME="Argonaut-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="Argonaut-watchOS"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6S"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator10.0"
    # - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"
    # - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK"
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage bootstrap --platform iOS,watchOS,tvOS --no-use-binaries
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;