osx_image: xcode7
language: objective-c
before_install: 
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose
script: xctool -scheme ArgonautTests -sdk iphonesimulator build test