osx_image: xcode7.2
language: objective-c
before_install: 
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage bootstrap --platform iOS,watchOS,tvOS --no-use-binaries
script: xctool -scheme ArgonautTests -sdk iphonesimulator build test
