language: objective-c
osx_image: xcode7.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Example.xcodeproj
  - IOS_FRAMEWORK_SCHEME="Argonaut-iOS"
  - TVOS_FRAMEWORK_SCHEME="Argonaut-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="Argonaut-watchOS"
  - IOS_SDK=iphonesimulator9.3
  - TVOS_SDK=appletvsimulator9.2
  - WATCHOS_SDK=watchsimulator2.2
  matrix:
    # - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    # - DESTINATION="OS=9.1,name=iPhone Plus"        SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    # - DESTINATION="OS=9.2,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="OS=9.3,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
    # - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"
    # - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK"
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.15.2/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
  - carthage bootstrap --platform iOS,watchOS,tvOS --no-use-binaries
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
